# Generated by Django 4.0.2 on 2022-02-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel_id', models.IntegerField(blank=True, null=True, verbose_name='responsavel_id')),
                ('datetime_begin', models.IntegerField(blank=True, null=True, verbose_name='datetime_begin')),
                ('datetime_end', models.IntegerField(blank=True, null=True, verbose_name='datetime_end')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='modelo')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='descrição')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='serialnumber')),
                ('RFID_tag_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='RFID_tag_id')),
                ('default_locale', models.CharField(blank=True, max_length=50, null=True, verbose_name='default_locale')),
                ('current_locale', models.CharField(blank=True, max_length=50, null=True, verbose_name='current_locale')),
                ('status', models.BooleanField(blank=True, null=True, verbose_name='status')),
            ],
        ),
    ]
