# Generated by Django 4.0.2 on 2022-02-16 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='last_name')),
                ('login', models.CharField(blank=True, max_length=100, null=True, verbose_name='login')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('privilegios', models.IntegerField(blank=True, choices=[(1, 'Usuário comum'), (2, 'Parte da equipe'), (3, 'Administrador')], null=True, verbose_name='privilegios')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='password')),
                ('password_confirmation', models.CharField(blank=True, max_length=100, null=True, verbose_name='password_confirmation')),
            ],
        ),
    ]
