# Generated by Django 4.0.2 on 2022-02-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_usuario_imagem_alter_usuario_privilegios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug'),
        ),
    ]
