# Generated by Django 4.0.2 on 2022-02-16 13:31

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_usuario_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='imagem',
            field=stdimage.models.StdImageField(default=0, upload_to='equipamentos', verbose_name='Imagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipamento',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug'),
        ),
    ]
