# Generated by Django 4.0.2 on 2022-02-17 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_equipamento_imagem_equipamento_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='datetime_begin',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='datetime_end',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='responsavel_id',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='Fim',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 9, 22, 59, 343607), help_text='Exemplo: 01/01/2020 13:00', verbose_name='Data e hora de fim da reserva'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='Inicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 8, 22, 59, 343607), help_text='Exemplo: 01/01/2020 12:00', verbose_name='Data e hora de início da reserva'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='responsavel',
            field=models.CharField(choices=[('Ritter, Cristian', 'Ritter, Cristian'), ('Paiva, Caetano', 'Paiva, Caetano')], default=0, max_length=80),
            preserve_default=False,
        ),
    ]
