# Generated by Django 4.0.2 on 2022-02-18 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_remove_agendamento_datetime_begin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='equipamento',
            field=models.CharField(choices=[('Sony, cam1', 'Sony, cam1'), ('sony, cs21', 'sony, cs21')], default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='Fim',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 9, 13, 30, 763560), help_text='Exemplo: 01/01/2020 13:00', verbose_name='Data e hora de fim da reserva'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='Inicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 8, 13, 30, 763560), help_text='Exemplo: 01/01/2020 12:00', verbose_name='Data e hora de início da reserva'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='responsavel',
            field=models.CharField(choices=[('admin', 'admin')], max_length=80),
        ),
    ]
